version: "3.7"
services:
  traefik:
    image: traefik:2.9
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      - --api=true
      - --api.dashboard=true
      - --api.insecure=true

      - --providers.docker=true
      - --providers.docker.swarmmode=true

      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=webmaster@launchpad.hu
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        # Dashboard
        - "traefik.http.routers.traefik-api.rule=Host(`traefik.dev.launchpad.hu`)"
        - "traefik.http.routers.traefik-api.entrypoints=https"
        - "traefik.http.routers.traefik-api.tls.certresolver=leresolver"
        - "traefik.http.routers.traefik-api.service=traefik"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik-api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$YI8L5CpywtbEevrdhVctIehU.lvHDpE5pg7JBWI8mYVDs6yDxlHzG"

          # global redirect to https
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=http"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

        # middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik-net:
    name: traefik-net
    attachable: true
    driver: overlay
